site_name: ☀️ OpenSUN 3D 🌍
nav:
  - Workshop Main Page: https://opensun3d.github.io
  - Challenge Track 1: track_1.md
  - Challenge Track 2: track_2.md
theme:
  name: material
  # logo:  
  site_url: https://opensun3d.github.io/cvpr24-challenge/
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # extra_css:
  # - stylesheets/extra.css

